//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tjoeGSTEntities : DbContext
    {
        public tjoeGSTEntities()
            : base("name=tjoeGSTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GSTR2_Header> GSTR2_Header { get; set; }
        public virtual DbSet<TBL_PRD_USERS> TBL_PRD_USERS { get; set; }
        public virtual DbSet<Purchase_datum> Purchase_Data { get; set; }
        public virtual DbSet<GSTR2_Data> GSTR2_Data { get; set; }
        public virtual DbSet<Purchase_Ticket> Purchase_Tickets { get; set; }
        public virtual DbSet<GST_State_Code> GST_State_Codes { get; set; }
        public virtual DbSet<AdminUser> AdminUsers { get; set; }
        public virtual DbSet<Admin_Clients> Admin_Clients { get; set; }
        public virtual DbSet<GSTCompareData> GSTCompareDatas { get; set; }
        public virtual DbSet<ModifiedData> ModifiedDatas { get; set; }
        public virtual DbSet<Sales_Ledger_datum> Sales_Ledger_Data { get; set; }
        public virtual DbSet<Sales_Ledger_EInvoice> Sales_Ledger_EInvoices { get; set; }
        public virtual DbSet<Sales_Ledger_EWay_Bill> Sales_Ledger_EWay_Bills { get; set; }
        public virtual DbSet<Sales_Ledger_Ticket> Sales_Ledger_Tickets { get; set; }
        public virtual DbSet<SLComparedData> SLComparedDatas { get; set; }
        public virtual DbSet<Client_Api_datum> Client_Api_Data { get; set; }
        public virtual DbSet<NoticeData> NoticeDatas { get; set; }
        public virtual DbSet<NoticeChat> NoticeChats { get; set; }
        public virtual DbSet<GSTR2_APIs_Data> GSTR2_APIs_Data { get; set; }
        public virtual DbSet<Sales_Ledger_EInvoice_APIs_datum> Sales_Ledger_EInvoice_APIs_Data { get; set; }
        public virtual DbSet<Sales_Ledger_EWay_Bill_APIs_datum> Sales_Ledger_EWay_Bill_APIs_Data { get; set; }
        public virtual DbSet<GSTR2_Token_Data> GSTR2_Token_Data { get; set; }
        public virtual DbSet<Sales_Ledger_Token_datum> Sales_Ledger_Token_Data { get; set; }
        public virtual DbSet<UserValidUpto> UserValidUptoes { get; set; }
        public virtual DbSet<PaymentDetail> PaymentDetails { get; set; }
    }
}
