//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_Api_datum
    {
        public string Client_Gstin { get; set; }
        public string API_IRIS_Username { get; set; }
        public string API_IRIS_Password { get; set; }
        public string Gst_Portal_Username { get; set; }
    }
}
