//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTCompareData
    {
        public string unique_value { get; set; }
        public Nullable<int> Row_Number { get; set; }
        public string Request_No { get; set; }
        public string Client_GSTIN { get; set; }
        public string Data_Source { get; set; }
        public string Financial_Year { get; set; }
        public string Year_Month { get; set; }
        public string Period { get; set; }
        public string Matching_Results { get; set; }
        public string Category { get; set; }
        public string Match_Type { get; set; }
        public string Invoice_Number { get; set; }
        public string Invoice_Date { get; set; }
        public string Supplier_GSTIN { get; set; }
        public string Supplier_Name { get; set; }
        public Nullable<decimal> Taxable_Value { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public Nullable<decimal> Total_Tax { get; set; }
    }
}
