//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTR2_Header
    {
        public string EXERT_ID_COL { get; set; }
        public string REF_EXERT_ID_COL { get; set; }
        public Nullable<bool> EXERT_STATUS { get; set; }
        public string EXERT_ROLL_CODE { get; set; }
        public string EXERT_ROLL_NAME { get; set; }
        public string EXERT_USER_CODE { get; set; }
        public string EXERT_USER_NAME { get; set; }
        public string EXERT_ENTITY_CODE { get; set; }
        public string EXERT_ENTITY_NAME { get; set; }
        public Nullable<System.DateTime> EXERT_ENTRY_DATE { get; set; }
        public string Client_GSTIN { get; set; }
        public string Request_No { get; set; }
        public Nullable<System.DateTime> Request_Date { get; set; }
        public string Txn_Period { get; set; }
        public string Ticket_Status { get; set; }
        public string No_Edit { get; set; }
    }
}
