//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTR2_APIs_Data
    {
        public long Unique_ID { get; set; }
        public string Client_Gstin { get; set; }
        public string Request_Number { get; set; }
        public string Session_ID { get; set; }
        public string Request_URL { get; set; }
        public string Request_Parameters { get; set; }
        public string Request_Headers { get; set; }
        public string Request_Body { get; set; }
        public string Response { get; set; }
        public string Response_Code { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Logged_Date_Time { get; set; }
    }
}
