//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTR2_Token_Data
    {
        public long uniqueId { get; set; }
        public string Client_Gstin { get; set; }
        public string Request_Number { get; set; }
        public string User_Name { get; set; }
        public string X_App_Key { get; set; }
        public string OTP { get; set; }
        public string Auth_Token { get; set; }
        public Nullable<System.DateTime> Auth_Token_Created_Datetime { get; set; }
        public string Expiry { get; set; }
        public string SEK { get; set; }
    }
}
