//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GSTR2_Data
    {
        public string EXERT_ID_COL { get; set; }
        public string REF_EXERT_ID_COL { get; set; }
        public Nullable<bool> EXERT_STATUS { get; set; }
        public string EXERT_ROLL_CODE { get; set; }
        public string EXERT_ROLL_NAME { get; set; }
        public string EXERT_USER_CODE { get; set; }
        public string EXERT_USER_NAME { get; set; }
        public string EXERT_ENTITY_CODE { get; set; }
        public string EXERT_ENTITY_NAME { get; set; }
        public Nullable<System.DateTime> EXERT_ENTRY_DATE { get; set; }
        public string Client_GSTIN { get; set; }
        public string GST_Reg_Type { get; set; }
        public string Supplier_GSTIN { get; set; }
        public string Supplier_Name { get; set; }
        public string Supplier_Invoice_No { get; set; }
        public Nullable<System.DateTime> Supplier_Invoice_Date { get; set; }
        public string IsRCMApplied { get; set; }
        public Nullable<decimal> Invoice_Value { get; set; }
        public Nullable<decimal> Item_Taxable_Value { get; set; }
        public Nullable<decimal> GST_Rate { get; set; }
        public Nullable<decimal> IGST_Value { get; set; }
        public Nullable<decimal> CGST_Value { get; set; }
        public Nullable<decimal> SGST_Value { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public string IsReturnFiled { get; set; }
        public string Txn_Period { get; set; }
        public string Request_No { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Modified { get; set; }
    }
}
