//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuItem
    {
        public long Id { get; set; }
        public string Email { get; set; }
        public string UserGstin { get; set; }
        public string UserName { get; set; }
        public string AllowMasterMenuItems { get; set; }
        public string AllowIrisMenuItems { get; set; }
    }
}
