//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModifiedData
    {
        public int S_No { get; set; }
        public string EXERT_ID_COL { get; set; }
        public string Invoiceno { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Supplier_GSTIN { get; set; }
        public Nullable<decimal> Tax_Amount { get; set; }
        public string Data_Source { get; set; }
        public Nullable<System.DateTime> Modified_DateTime { get; set; }
        public string Request_No { get; set; }
        public string Client_GSTIN { get; set; }
    }
}
