//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeData
    {
        public int Unique_Id { get; set; }
        public string Request_Number { get; set; }
        public string Client_Gstin { get; set; }
        public Nullable<System.DateTime> Created_Datetime { get; set; }
        public string Notice_Title { get; set; }
        public Nullable<System.DateTime> Notice_Datetime { get; set; }
        public string Priority { get; set; }
        public string Notice_Description { get; set; }
        public string status { get; set; }
        public string Client_Name { get; set; }
        public Nullable<System.DateTime> Closed_Datetime { get; set; }
        public string FileName { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
        public string ClosedBy { get; set; }
    }
}
