//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoticeChat
    {
        public int Unique_Id { get; set; }
        public string Request_Number { get; set; }
        public string Client_Gstin { get; set; }
        public string Source { get; set; }
        public string Name { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Message_Datetime { get; set; }
        public Nullable<bool> IsRead { get; set; }
    }
}
