//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public long Id { get; set; }
        public string ClientName { get; set; }
        public string ClientGstin { get; set; }
        public string ClientEmail { get; set; }
        public string ClientPhone { get; set; }
        public string ClientAddress { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Days { get; set; }
        public string OrderId { get; set; }
        public string PaymentId { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public string TransactionId { get; set; }
    }
}
