//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_datum
    {
        public string EXERT_ID_COL { get; set; }
        public string REF_EXERT_ID_COL { get; set; }
        public Nullable<bool> EXERT_STATUS { get; set; }
        public string EXERT_ROLL_CODE { get; set; }
        public string EXERT_ROLL_NAME { get; set; }
        public string EXERT_USER_CODE { get; set; }
        public string EXERT_USER_NAME { get; set; }
        public string EXERT_ENTITY_CODE { get; set; }
        public string EXERT_ENTITY_NAME { get; set; }
        public Nullable<System.DateTime> EXERT_ENTRY_DATE { get; set; }
        public string Client_GSTIN { get; set; }
        public string Request_No { get; set; }
        public string Txn_Period { get; set; }
        public string Supplier_GSTIN { get; set; }
        public string Supplier_Name { get; set; }
        public string Invoiceno { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public Nullable<decimal> Taxable_Value { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> Integrated_Tax { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public string Remarks { get; set; }
        public string Day { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Modified { get; set; }
    }
}
