//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Ledger_EWay_Bill
    {
        public string Unique_Value { get; set; }
        public string Request_Number { get; set; }
        public string EWB_Number { get; set; }
        public Nullable<System.DateTime> EWB_Date { get; set; }
        public string Date { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Supply_Type { get; set; }
        public string Doc_Number { get; set; }
        public Nullable<System.DateTime> Doc_Date { get; set; }
        public string Doc_Type { get; set; }
        public string TO_GSTIN { get; set; }
        public string status { get; set; }
        public string No_of_Items { get; set; }
        public string Main_HSN_Code { get; set; }
        public string Main_HSN_Desc { get; set; }
        public Nullable<decimal> Assessable_Value { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> Total_Invoice_Value { get; set; }
        public Nullable<System.DateTime> Valid_Till_Date { get; set; }
        public string Gen_Mode { get; set; }
        public string Client_Gstin { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CESS { get; set; }
    }
}
