//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Ledger_datum
    {
        public string Unique_Value { get; set; }
        public string Request_Number { get; set; }
        public string Sno { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Date { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_GSTIN { get; set; }
        public string State_To_Supply { get; set; }
        public Nullable<decimal> Taxable_Amount { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string GST_Rate { get; set; }
        public string HSN_SAC_Code { get; set; }
        public string Quantity { get; set; }
        public string Units { get; set; }
        public string Material_Description { get; set; }
        public string Type_Of_Invoice { get; set; }
        public string Client_GSTIN { get; set; }
        public string IRN { get; set; }
    }
}
