//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Ledger_Token_datum
    {
        public long uniqueId { get; set; }
        public string ClientGstin { get; set; }
        public string RequestNumber { get; set; }
        public string EInvoiceAuthToken { get; set; }
        public Nullable<System.DateTime> EInvoiceAuthTokenCreatedDatetime { get; set; }
        public string EInvoiceSek { get; set; }
        public string EInvoiceTokenExpiry { get; set; }
    }
}
