//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Ledger_Ticket
    {
        public string Unique_Value { get; set; }
        public string Request_Number { get; set; }
        public string Client_Name { get; set; }
        public string CLient_Email { get; set; }
        public string Client_Gstin { get; set; }
        public Nullable<System.DateTime> Request_Created_Date { get; set; }
        public Nullable<System.DateTime> Request_Updated_Date { get; set; }
        public Nullable<System.DateTime> Request_Complete_Date { get; set; }
        public string File_Name { get; set; }
        public string EInvoice_File_Name { get; set; }
        public string EWay_Bill_File_Name { get; set; }
        public string Edit { get; set; }
        public string Financial_Year { get; set; }
        public string Period_Type { get; set; }
        public string Period { get; set; }
        public string Ticket_Status { get; set; }
    }
}
