//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales_Ledger_EInvoice
    {
        public string Unique_Value { get; set; }
        public string Recipient_GSTIN { get; set; }
        public string Receiver_Name { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<System.DateTime> Invoice_date { get; set; }
        public string Date { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<decimal> Invoice_Value { get; set; }
        public string Place_Of_Supply { get; set; }
        public string Reverse_Charge { get; set; }
        public string Invoice_Type { get; set; }
        public string E_Commerce_GSTIN { get; set; }
        public string Tax_Rate { get; set; }
        public Nullable<decimal> Taxable_Value { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public string IRN { get; set; }
        public Nullable<System.DateTime> IRN_Date { get; set; }
        public string E_invoice_status { get; set; }
        public string Request_Number { get; set; }
        public string Client_Gstin { get; set; }
        public string Applicable_Tax_Rate { get; set; }
        public Nullable<System.DateTime> GSTR1_Auto_Population_Deletion_Date { get; set; }
        public string GSTR1_Auto_Population_Deletion_Status { get; set; }
        public string Error_In_Auto_Population_Deletion { get; set; }
    }
}
