//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SLComparedData
    {
        public int uni { get; set; }
        public string Unique_Value { get; set; }
        public string Client_Gstin { get; set; }
        public string Request_Number { get; set; }
        public Nullable<int> S_No { get; set; }
        public string Invoice_Number { get; set; }
        public Nullable<System.DateTime> Invoice_Date { get; set; }
        public string Customer_Name { get; set; }
        public string Customer_Gstin { get; set; }
        public string Place_of_Supply { get; set; }
        public Nullable<decimal> Taxable_Amount { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> IGST { get; set; }
        public Nullable<decimal> CESS { get; set; }
        public Nullable<decimal> Total_Amount { get; set; }
        public string GST_Rate { get; set; }
        public string Type_Of_Invoice { get; set; }
        public string Category { get; set; }
        public string DataSource { get; set; }
        public string Match_Type { get; set; }
        public string Compare { get; set; }
        public string Period { get; set; }
    }
}
