//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CAF.GstMatching.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_PRD_USERS
    {
        public string EXERT_ID_COL { get; set; }
        public string REF_EXERT_ID_COL { get; set; }
        public Nullable<bool> EXERT_STATUS { get; set; }
        public string USER_CODE { get; set; }
        public string USER_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string ROLE_CODE { get; set; }
        public string ROLE_NAME { get; set; }
        public string LANGUAGE { get; set; }
        public string Themes { get; set; }
        public string EXERT_ENTITY_CODE { get; set; }
        public string EXERT_ENTITY_NAME { get; set; }
        public string EXERT_USER_CODE { get; set; }
        public string EXERT_USER_NAME { get; set; }
        public string EXERT_ROLL_CODE { get; set; }
        public string EXERT_ROLL_NAME { get; set; }
        public string Confirm_Password { get; set; }
        public string Default_page { get; set; }
        public string Page_Layout_Type { get; set; }
        public Nullable<System.DateTime> EXERT_ENTRY_DATE { get; set; }
        public string Entity_Code { get; set; }
        public string Entity_Name { get; set; }
        public string Email { get; set; }
        public string Designation { get; set; }
        public Nullable<decimal> Lower_Limit { get; set; }
        public Nullable<decimal> Upper_Limit { get; set; }
        public string Currency { get; set; }
        public string Type_ { get; set; }
        public string Address { get; set; }
        public string Department { get; set; }
        public string LoginAttempt { get; set; }
        public Nullable<decimal> RowsPerPage { get; set; }
        public Nullable<decimal> LkUpRowsPerPage { get; set; }
        public string Full_Name { get; set; }
        public string Mobile_PIN { get; set; }
        public string Department_HOD { get; set; }
        public Nullable<System.DateTime> LastPasswordSet { get; set; }
        public string ExpiryTimeSpan { get; set; }
        public string ForgotPasswordToken { get; set; }
        public Nullable<decimal> Failure_Count { get; set; }
        public Nullable<System.DateTime> Last_Locked_Date { get; set; }
        public string Password_Changed { get; set; }
        public Nullable<decimal> Failure_Count1 { get; set; }
        public Nullable<System.DateTime> Last_Locked_Date1 { get; set; }
        public string Status { get; set; }
    }
}
